### ISSUE TITLE
Duplicate count

### ISSUE THREAD

**Issue by LVS04** [WhiteKarma/NalandaERP#18]
Hello guy!
1/ The duplicate system seems to take into account the first and last name but not the email...?
2/ For similarity, if last name start with "an" the system includes as duplicate also the name having "an" inside like "lazano" which is not a duplicate... :)

**Comment by LVS04** [comment]
A third one...
3/ The button "new" next the "create" one is very confusing and for me useless.... ;-)

**Comment by WhiteKarma** [comment]
OK i will address each point:

1. The e-mail has it's own duplication validation system right there on the field, because in my view it is so fundamental that it is to be taken into account even if none of the other fields match. So the system regards it as prioritary and *exact* rather than a similarity or a possible duplicate.

2. There are 3 possibilities for matching a string ( in the beginning, in all of the string, or at the end ). I went for the option most suitable to find a similarities even if people did not type it right at the first time.  For the similarities match, all the fields are considered and each word is considered with its similarity individually and the matches are found only if they match *all the words* in any place. But the system only **suggests similarities which is different and more broad than finding exact duplicates** and the main idea was that in practice, there are a lot of typing mistakes and letters somehow have the tendency to get changed and be put out of place. So for example, to use your example, if a person is in doubt of how to write "La**z**ano" ( which is really written as "La**s**ano" ) but the person knows the sound "ano" the system would find the similar match and he would not duplicate. Scenarios like this are also possible. 

3. The button "New" is useful when for example you insert a contact and you want to insert another, for it cleans all the fields.

Thank you

**Comment by LVS04** [comment]
1. Very good but not a reason to exclude it from the global validation system.
2. I understand the spelling mistake problem but at the end you have a lot of pollution in the duplicate counting, so I just wonder how it is for the people that will use the system.
3. Ok I got it!! :)
Thanks!!

**Comment by WhiteKarma** [comment]
1. To be discussed in the testers meeting this week.
2. About the pollution on the duplicates: I checked this in Production ( in the office ) already with part of the real data and it does not happen. Another note, i was able to find toine's e-mail just by including toine ( his email starts with a 2 ). This search is much more flexible, i can see that it is missing in a lot of places, on my phone for example; which forces me to know the beginning of the contact name that chose for it.
